apiVersion: v1
kind: PersistentVolume
metadata:
  name: examplepv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: examplenfs
  nfs:
    path: /home/hifi/data
    server: 100.101.56.162
