apiVersion: apps/v1
kind: Deployment
metadata:
  name: exampledeploy4service
spec:
  replicas: 3
  selector:
    matchLabels:
      example: ex4service
  template:
    metadata:
      labels:
        example: ex4service
    spec:
      containers:
      - name: pythonservice
        image: python:3.7
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c']
        args: ['echo "<p>The host is $(hostname)<p>" > index.html; python -m http.server 80']
        ports:
        - name: http
          containerPort: 80
