apiVersion: apps/v1
kind: Deployment
metadata:
  name: exampledeploy
spec:
  replicas: 5
  selector:
    matchLabels:
      example: deploy4nginx
  template:
    metadata:
      labels:
        example: deploy4nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.9.0
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
