apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: exampledaemon
spec:
  selector:
    matchLabels:
      example: deploy4httpd
  template:
    metadata:
      labels:
        example: deploy4httpd
    spec:
      containers:
      - name: httpd
        image: httpd:2.2
        ports:
        - containerPort: 80
          hostPort: 8082
          protocol: TCP
