apiVersion: v1
kind: Service
metadata:
  name: examplenodeport
spec:
  selector:
    example: ex4service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30001
  type: NodePort
